### ISSUE TITLE
挂载后可以复制出来，但是直接拖入不行，不知道是我姿势不对还是不支持拖入呢

### ISSUE THREAD

**Issue by blackness3** [AlistGo/desktop-release#25]
RT
我以为挂在和onedrive效果差不多可以直接拖入呢
请问是不支持还是我没装好。

**Comment by Xhofe** [comment]
应该可以拖入 
挂载那里的日志报什么错

**Comment by heaid** [comment]
我测试了下 阿里盘和 onedrive可以拖入，就是天翼云不行，
![image](https://github.com/alist-org/desktop-release/assets/57695239/f3317df8-2790-4bf5-a198-86ecc6cdfc53)
![image](https://github.com/alist-org/desktop-release/assets/57695239/23dcc18c-bab4-4065-a5e3-696c2e33651f)

**Comment by Xhofe** [comment]
> 我测试了下 阿里盘和 onedrive可以拖入，就是天翼云不行， ![image](https://user-images.githubusercontent.com/57695239/258425092-f3317df8-2790-4bf5-a198-86ecc6cdfc53.png) ![image](https://user-images.githubusercontent.com/57695239/258425115-23dcc18c-bab4-4065-a5e3-696c2e33651f.png)

天翼云盘还是天翼云盘PC。以及上传的时候首页的日志报什么错

**Comment by heaid** [comment]
是天翼云盘客户端挂载的

**Comment by Xhofe** [comment]
我试了一下没能复现，可以发一份你上传的文件吗

**Comment by heaid** [comment]
不是我试过图片 png 表格 xlsx   和没后缀的文件  还有html的都不行

**Comment by heaid** [comment]
[iShot_2023-08-04_23.15.45.mp4.zip](https://github.com/alist-org/desktop-release/files/12262145/iShot_2023-08-04_23.15.45.mp4.zip)
我录了个视频 你解压看看  因为视频没法直接拖入进来，

**Comment by heaid** [comment]
还有我测试了  从网页端 点上传，是可以成功上传到天翼云盘的。

**Comment by xhofe** [comment]
远程看一下 面包多私信
